name: build

on:
  push: 
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'  
    - name: Cache
      uses: actions/cache@v2.1.5
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/.m2
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-${{ hashFiles('pom.xml') }}
    - name: Cache SonarCloud packages
      uses: actions/cache@v2.1.5
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: SonarCloud Scan
      if: github.repository == 'maruTA-bis5/primefaces-excella-exporter' && github.ref == 'refs/heads/master'
      run: mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=maruTA-bis5_primefaces-excella-exporter -Dsonar.organization=maruta-bis5-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{secrets.SONAR_TOKEN}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
